spring:
  datasource:
    url: jdbc:h2:mem:library-back-end
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true

server:
  port: 8082

springdoc:
  swagger-ui:
    operationsSorter: method